name: upload_file
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  firebase_storage: ^7.0.0
  firebase_core: ^0.7.0
  flutter_local_notifications: ^4.0.0
  image_picker: ^0.6.7+22
  fluttertoast: ^7.1.6
  flutter_isolate: ^1.0.0+14
  workmanager: ^0.2.3
  flutter_uploader: ^2.0.0-beta.6

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true


